### ISSUE TITLE
Unauthorized use of the "PCAN" trademark

### ISSUE THREAD

**Issue by PEAK-KWR** [tsabelmann/pcan-basic#6]
Dear Mr. Sabelmann

We discovered your crate, **pcan-basic**, on [crates.io](https://crates.io/crates/pcan-basic). Please note that **PCAN** is a registered trademark of **PEAK-System Technik GmbH**.

We would like to kindly request you to change the name of your package/library/files. Please do not use our registered trademark **PCAN** in file names, description text or other publications. We ask that you make the changes by May 31, 2024.

If we discover further trademark infringements in your software, libraries, files, etc. (including file names) after this period, we reserve the right to take legal action against you.

Thank you for your understanding.

Best regards
PEAK-System Technik GmbH

**Comment by birdistheword96** [comment]
@PEAK-KWR, are you planning to release a rust crate so that rust developers can use your equipment, or are you just trying to alienate the open source community for no reason? This repo gives clear credit, refers to your existing license, and the ability to use your hardware with Rust was part of the reason my company to started buying these instead of more Vector Dongles/Licences. 

If you are going to try and crush the open source community, then what incentive is there for us to buy your products over the multitude of other options available?

**Comment by PEAK-KWR** [comment]
@birdistheword96, it has nothing to do with open source alienation or similar. We do not want to crush anybody, so calm down. 

As I wrote, the problem is just the name. **PCAN** is a registered trademark that **can only be used** by PEAK-System, no more no less. The crate can perfectly be kept, just with a different name since: 

1. We already have a product with this name, 
2. PCAN is a reservedtrademark. 

And to answer your question, yes, we are planning to implement also a rust crate.

**Comment by birdistheword96** [comment]
That's a fair response, but since this crate offers a wrapper around your 'PCAN' API, how would you suggest it gets named? 

For it to be found by developers wanting to use your devices with Rust, this identification is crucial. All credit was given to you in the main README, and I understand that the word is trademarked, but its not being used for anything other than to identify its use with YOUR intellectual property. Is just missing a few TM's scattered through the docs?

**Comment by PEAK-KWR** [comment]
@tsabelmann are you and @birdistheword96 the same person? If yes, just to let you know that we do not need to handle this in public. You can write to info[at]peak-system.com. If not, please, since this is your crate, I ask you to participate and to confirm that you have taken note of this. 

Thanks you

**Comment by PEAK-KWR** [comment]
@birdistheword96, As said, we have already a product with that name, and the name is also our property.  Please understand that. We have no problem with the project or that it is kept here, also not problem telling that it supports our PCAN-Basic API. But the files and/or projects cannot be called "PCAN" or "PCAN-Basic". 

Regarding a name, what about **"rust-can"**? As I see, it is not used and let you open the possibility to support another verndors in the same file. There are other packages implementation that do so, for instance [Python-Can](https://python-can.readthedocs.io/en/stable/interfaces/pcan.html).

**Comment by tsabelmann** [comment]
Hello @PEAK-KWR, I just wrote to info[at]peak-system.com to resolve this matter in a timely and friendly manner. In python-can PCAN is explicitly mentioned. Is this okay according to your trademark policies?

**Comment by tsabelmann** [comment]
Hello @PEAK-KWR, I have another question. How could I refer to PCAN without using PCAN such that it is apparent that PCAN is meant? python-can is using PCAN in its enum names to name one usage. Do you have any suggestions?

**Comment by PEAK-KWR** [comment]
Hello,

thanks for you E-Mail. We will answer you soon. We will answer you there the question regarding PCAN too.

**Comment by PEAK-KWR** [comment]
Hello,

we found a solution to the problem. Thanks @tsabelmann for your understanding and collaboration.
